const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const services=[
{id:'ppf-front',name:'PPF · front impact package',desc:'Bonnet, bumper, front fenders & mirrors',time:'1–2 days',base:25000,cat:'protection'},
{id:'ppf-full',name:'PPF · full body gloss',desc:'Clear TPU film · coverage agreed after inspection',time:'3–5 days',base:65000,cat:'protection'},
{id:'ppf-satin',name:'PPF · full body satin',desc:'A satin finish with full-body film coverage',time:'3–5 days',base:85000,cat:'protection'},
{id:'ceramic',name:'Ceramic coating',desc:'Paint preparation & professional coating application',time:'2–3 days',base:18000,cat:'protection'},
{id:'glass',name:'Glass coating',desc:'Windscreen preparation & hydrophobic treatment',time:'2–3 hours',base:2000,cat:'protection'},
{id:'polish',name:'Paint correction · single stage',desc:'Light swirl correction & gloss enhancement',time:'6–8 hours',base:5000,cat:'detailing'},
{id:'correction',name:'Paint correction · multi stage',desc:'Deeper refinement for weathered paintwork',time:'1–2 days',base:10000,cat:'detailing'},
{id:'interior',name:'Interior deep detailing',desc:'Seats, carpets, dashboard, trims & sanitisation',time:'5–7 hours',base:3500,cat:'detailing'},
{id:'headlights',name:'Headlight restoration',desc:'Both headlights · haze correction & protection',time:'2–3 hours',base:1500,cat:'detailing'},
{id:'foam',name:'Signature foam wash',desc:'Foam wash, wheels, dry-down & tyre dressing',time:'45–60 min',base:499,cat:'washing'},
{id:'premium',name:'Premium wash & cabin clean',desc:'Exterior wash, vacuum, dashboard & glass',time:'60–90 min',base:899,cat:'washing'},
{id:'engine',name:'Engine bay detailing',desc:'Controlled cleaning & dressing of accessible areas',time:'1–2 hours',base:1200,cat:'washing'},
{id:'dent',name:'Minor dent repair',desc:'Per panel · repair method subject to inspection',time:'1–2 days',base:2000,cat:'repair'},
{id:'paint',name:'Panel denting & painting',desc:'Per panel · surface preparation, paint & finishing',time:'2–3 days',base:4500,cat:'repair'},
{id:'repaint',name:'Complete body repaint',desc:'Exterior repaint · scope and colour agreed first',time:'7–12 days',base:45000,cat:'repair'},
{id:'maintenance',name:'Periodic mechanical service',desc:'Basic labour & inspection · parts and fluids extra',time:'4–6 hours',base:2500,cat:'repair'}];
let filter='all',multiplier=1.2,toastTimer,sceneIndex=-1,craftIndex=-1;
const money=n=>'₹'+Math.round(n).toLocaleString('en-IN');
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2200)}
function openEnquiry(service='Studio consultation'){const dlg=$('#inquiry-dialog'),select=$('#inquiry-service');if(![...select.options].some(o=>o.value===service)){const option=document.createElement('option');option.value=service;option.textContent=service;select.append(option)}select.value=service;$('#inquiry-form').hidden=false;$('#inquiry-result').hidden=true;$('#inquiry-feedback').textContent='';dlg.showModal();setTimeout(()=>$('#inquiry-name').focus(),100)}
function price(service){return Math.round(service.base*multiplier/10)*10}
function renderCatalogue(){$('#catalogue-panel').innerHTML=services.filter(s=>filter==='all'||s.cat===filter).map(s=>`<article class="catalogue-row"><div><h3>${s.name}</h3><p>${s.desc}</p></div><span class="time">${s.time}</span><span class="price">${money(price(s))}</span><button class="request-service" data-service="${s.name}" aria-label="Ask the studio about ${s.name}">Enquire</button></article>`).join('');}
function setFilter(next,focus=false){filter=next;$$('[data-filter]').forEach(b=>{const active=b.dataset.filter===next;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;if(active&&focus)b.focus()});$('#catalogue-panel').setAttribute('aria-labelledby','tab-'+next);renderCatalogue()}
$$('[data-filter]').forEach((b,i,all)=>{b.onclick=()=>setFilter(b.dataset.filter);b.onkeydown=e=>{let n=i;if(e.key==='ArrowRight')n=(i+1)%all.length;else if(e.key==='ArrowLeft')n=(i+all.length-1)%all.length;else if(e.key==='Home')n=0;else if(e.key==='End')n=all.length-1;else return;e.preventDefault();setFilter(all[n].dataset.filter,true)}});
$$('[data-category]').forEach(a=>{a.addEventListener('click',()=>{setFilter(a.dataset.category);const value={protection:'PPF and paint protection',detailing:'Paint correction or ceramic coating',washing:'Wash or interior detailing',repair:'Denting, painting or restoration'}[a.dataset.category];if(a.matches('.request-service'))openEnquiry(value)})});
$('#vehicle').onchange=e=>{multiplier=Number(e.target.value);renderCatalogue()};
$('#catalogue-panel').onclick=e=>{const b=e.target.closest('[data-service]');if(b)openEnquiry(b.dataset.service)};
$$('.enquiry-open').forEach(b=>b.onclick=()=>openEnquiry(b.dataset.service||'Studio consultation'));
$('#inquiry-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),name=String(f.get('name')).trim(),phone=String(f.get('phone')).trim(),vehicle=String(f.get('vehicle')).trim(),service=String(f.get('service')).trim(),notes=String(f.get('notes')).trim();const message=['Hello APEX Auto Studio,','',`My name is ${name}.`,`I would like to discuss: ${service}.`,vehicle?`My vehicle: ${vehicle}.`:null,notes?`A little more about what I need: ${notes}`:null,`You can reach me at ${phone}.`,'','Could you please advise on an inspection and suitable next steps?'].filter(Boolean).join('\n');$('#inquiry-message').value=message;$('#inquiry-form').hidden=true;$('#inquiry-result').hidden=false;$('#inquiry-feedback').textContent='Your enquiry is ready to copy. It has not been sent.';$('#copy-inquiry').focus()});
$('#copy-inquiry').onclick=async()=>{const msg=$('#inquiry-message');try{await navigator.clipboard.writeText(msg.value);$('#inquiry-feedback').textContent='Enquiry copied. You can paste it into your preferred contact channel.';toast('Enquiry copied')}catch{msg.focus();msg.select();$('#inquiry-feedback').textContent='Select and copy the message above to share it.'}};
$('#credits-open').onclick=()=>$('#credits-dialog').showModal();$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
$('.menu-toggle').onclick=()=>{const open=$('#nav').classList.toggle('open');$('.menu-toggle').setAttribute('aria-expanded',String(open));$('.menu-toggle').setAttribute('aria-label',open?'Close menu':'Open menu');$('.menu-toggle').textContent=open?'×':'☰'};$$('#nav a').forEach(a=>a.onclick=()=>{$('#nav').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false');$('.menu-toggle').textContent='☰'});
const experience=$('.experience'),stage=$('.stage'),craftSection=$('.craft-journey'),craftStage=$('.craft-stage');
function scroll(){const p=Math.max(0,Math.min(1,-experience.getBoundingClientRect().top/(experience.offsetHeight-stage.offsetHeight)));window.apexScroll=p;$('#header').classList.toggle('scrolled',scrollY>35);$('.scene-progress i').style.width=(p*100)+'%';const i=Math.min(5,Math.floor(p*6));if(i!==sceneIndex){sceneIndex=i;$$('[data-scene]').forEach(el=>{const active=Number(el.dataset.scene)===i;el.classList.toggle('active',active);el.inert=!active;el.setAttribute('aria-hidden',String(!active))});$$('[data-step]').forEach(el=>el.classList.toggle('active',Number(el.dataset.step)===i))}
const cp=Math.max(0,Math.min(1,-craftSection.getBoundingClientRect().top/(craftSection.offsetHeight-craftStage.offsetHeight)));window.apexCraftScroll=cp;const ci=Math.min(3,Math.floor(cp*4));if(ci!==craftIndex){craftIndex=ci;$$('[data-craft]').forEach(el=>{const active=Number(el.dataset.craft)===ci;el.classList.toggle('active',active);el.inert=!active});$$('[data-craft-step]').forEach(el=>el.classList.toggle('active',Number(el.dataset.craftStep)===ci));$('#craft-current').textContent=String(ci+1).padStart(2,'0')}$('#detail-canvas').style.setProperty('--craft-progress',cp);}
addEventListener('scroll',scroll,{passive:true});addEventListener('resize',scroll);$$('[data-step]').forEach(b=>b.onclick=()=>{const p=(Number(b.dataset.step)+.02)/6;window.scrollTo({top:experience.offsetTop+(experience.offsetHeight-stage.offsetHeight)*p,behavior:reduced?'instant':'smooth'})});$$('[data-craft-step]').forEach(b=>b.onclick=()=>{const p=(Number(b.dataset.craftStep)+.05)/4;window.scrollTo({top:craftSection.offsetTop+(craftSection.offsetHeight-craftStage.offsetHeight)*p,behavior:reduced?'instant':'smooth'})});
$$('.swatch').forEach(b=>b.onclick=()=>{$$('.swatch').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});window.dispatchEvent(new CustomEvent('apex-color',{detail:b.dataset.color}))});
if('IntersectionObserver'in window&&!reduced){document.body.classList.add('motion-ready');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});$$('.reveal').forEach(e=>observer.observe(e))}
let loaderFrame,loaderTimeout;window.apexLoading=false;function ignition(){if(reduced){$('#loader').classList.add('hidden');return}cancelAnimationFrame(loaderFrame);clearTimeout(loaderTimeout);const l=$('#loader');l.classList.remove('hidden','playing');void l.offsetWidth;l.classList.add('playing');const start=performance.now();window.apexLoading=true;window.apexIgnitionStart=start;function tick(t){const p=Math.min((t-start)/3000,1);$('#load-number').textContent=String(Math.floor(p*100)).padStart(2,'0');if(p<1)loaderFrame=requestAnimationFrame(tick)}loaderFrame=requestAnimationFrame(tick);loaderTimeout=setTimeout(()=>{l.classList.add('hidden');window.apexLoading=false},3000)}
$('#replay').onclick=ignition;$('#year').textContent=new Date().getFullYear();renderCatalogue();scroll();ignition();
